POST http://127.0.0.1:3001/instPosts/insertPostDetails HTTP/1.1
content-type: application/json


{
  "InstId": "MrX",
  "ProfilePhotoUrl": "profile Photo url here",
  "PostCount": 2,
  "InstPosts": [
    {
      "PostDescription": "coding...",
      "PostPhotoUrl":"post Photo url here",
      "Location": "home",
      "LikesCount": 10,
      "CommentCount": 1,
      "PostDate": "2022-2-07",
      "Comments": [
        {
          "InstId": "Mr Y",
          "CommentText": "As usual coding at home..",
          "CommentToId": "MrX"
        }]
    }]
}
    
###

GET http://127.0.0.1:3001/instPosts/findPostDetails HTTP/1.1
content-type: application/json


###

POST http://127.0.0.1:3001/instPosts/insertPostDetails HTTP/1.1
content-type: application/json


{
  "InstId": "MrX",
  "ProfilePhotoUrl": "profile Photo url",
  "PostDescription": "coding...",
  "PostPhotoUrl":"post Photo url here",
  "Location": "home",
  "PostDate": "2022-2-07"
}



###

POST http://127.0.0.1:3001/instPosts/insertCommentDetails HTTP/1.1
content-type: application/json


{
  "InstId": "MrX",
  "PostPhotoUrl":"post Photo url here",
  "CommentInstId": "Mr Y",
  "CommentText": "As usual coding at home..",
  "CommentToId": "MrX"
}

###

POST http://127.0.0.1:3001/instPosts/addNewLike HTTP/1.1
content-type: application/json


{
  "InstId": "MrX",
  "PostPhotoUrl":"post Photo url here"
}

###

POST http://127.0.0.1:3001/instPosts/removeNewLike HTTP/1.1
content-type: application/json


{
  "InstId": "MrX",
  "PostPhotoUrl":"post Photo url here"
}

###


POST http://127.0.0.1:3001/instPosts/deletePostDetails HTTP/1.1
content-type: application/json


{
  "InstId": "MrX",
  "PostPhotoUrl":"post Photo url here2"
}