const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const postSchema = new Schema({
  // id is generated by mongodb
  InstId: String,
  ProfilePhotoUrl: String,
  PostCount: {
    type: Number,
    default: 1,
  },
  InstPosts: [
    {
      PostDescription: String,
      PostPhotoUrl: String,
      Location: String,
      LikesCount: {
        type: Number,
        default: 0,
      },
      CommentCount: {
        type: Number,
        default: 0,
      },
      PostDate: {
        type: Date,
        default: Date.now,
      },
      Comments: [
        {
          InstId: String,
          CommentText: String,
          CommentToId: String,
        },
      ],
    },
  ],
});
const PostModel = mongoose.model("postModels", postSchema);

module.exports = PostModel;
