const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const postSchema = new Schema({
  // id is generated by mongodb
  InstId: {
    type: String,
    required: true,
  },
  ProfilePhotoUrl: {
    type: String,
    required: true,
  },
  PostCount: {
    type: Number,
    required: true,
  },
  InstPosts: [
    {
      PostDescription: String,
      PostPhotoUrl: {
        type: String,
        required: true,
      },
      Location: String,
      LikesCount: {
        type: Number,
        required: true,
      },
      CommentCount: {
        type: Number,
        required: true,
      },
      PostDate: {
        type: Date,
        required: true,
      },
      Comments: [
        {
          InstId: {
            type: String,
            required: true,
          },
          CommentText: {
            type: String,
            required: true,
          },
          CommentToId: {
            type: String,
            required: true,
          },
        },
      ],
    },
  ],
});
const PostModel = mongoose.model("postModels", postSchema);

module.exports = PostModel;
