const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const postSchema = new Schema({
  // id is generated by mongodb
  InstId: String,
  ProfilePhotoUrl: String,
  PostCount: Number,
  InstPosts: [
    {
      PostDescription: String,
      PostPhotoUrl: String,
      Location: String,
      LikesCount: Number,
      CommentCount: Number,
      PostDate: Date,
      Comments: [
        {
          InstId: String,
          CommentText: String,
          CommentToId: String,
        },
      ],
    },
  ],
});
const PostModel = mongoose.model("postModels", postSchema);

module.exports = PostModel;
